function h = uiProgressBar(varargin)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
if ishandle(varargin{1}) && size(varargin,2) > 1
    ax = varargin{1};
    value = varargin{2};
    p = get(ax,'Child');
    x = get(p,'XData');
    x(3:4) = value;
    set(p,'XData',x)
    return
end

bg_color = 'w';
fg_color = 'r';
h = axes('Units','pixels',...
    'XLim',[0 1],'YLim',[0 1],...
    'XTick',[],'YTick',[0 1],...
    'Color',bg_color,...
    'XColor',bg_color,'YColor',bg_color,...
    'Parent',varargin{1});
patch([0 0 0 0],[0 1 1 0],fg_color,...
    'Parent',h,...
    'EdgeColor','none',...
    'EraseMode','none');
end
